In [4]:
import numpy as np
# X = (hours studying, hours sleeping), y = score on test, xPredicted = 4 hours studying & 8 hours sleeping (input data for prediction)
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
xPredicted = np.array(([4,8]), dtype=float)
X = X/np.amax(X, axis=0)
xPredicted = xPredicted/np.amax(xPredicted, axis=0)
y = y/100 # max test score is 100
class Neural_Network(object):
    def __init__(self):
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize)
        # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize)
        # (3x1) weight matrix from hidden to output layer

    def forward(self, X):
        self.z = np.dot(X, self.W1)
        self.z2 = self.sigmoid(self.z) # activation function
        self.z3 = np.dot(self.z2, self.W2) # dot product of hidden layer (z2)andsecondsetof 3x1 weights
        o = self.sigmoid(self.z3) # final activation function
        return o
    
    def sigmoid(self, s): 
        return 1/(1+np.exp(-s))
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def backward(self, X, y, o):
        self.o_error = y - o # error in output
        self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error
        self.z2_error = self.o_delta.dot(self.W2.T) # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error
        self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights
    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)
    def saveWeights(self):
        np.savetxt("w1.txt", self.W1, fmt="%s")
        np.savetxt("w2.txt", self.W2, fmt="%s")
    def predict(self):
        print("Predicted data based on trained weights: ")
        print("Input (scaled): \n" + str(xPredicted))
        print("Output: \n" + str(self.forward(xPredicted)))
NN = Neural_Network()
for i in range(1000): # trains the NN 1,000 times
    print("# " + str(i) + "\n")
    print("Input (scaled): \n" + str(X))
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" + str(NN.forward(X)))
    print("Loss: \n" + str(np.mean(np.square(y - NN.forward(X)))))
    # mean sum squared loss
    print("\n")
    NN.train(X, y)
    NN.saveWeights()
    NN.predict()

# 0

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.43335872]
 [0.40364726]
 [0.42573373]]
Loss: 
0.2202069108943162


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.51541622]
# 1

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.52026371]
 [0.48472849]
 [0.51435832]]
Loss: 
0.1472414935302533


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.58596555]
# 2

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.59124651]
 [0.55258925]
 [0.5869896 ]]
Loss: 
0.0981318430574407


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.63946716]
# 3

Input (scaled): 
[[0.66666667 1.   

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.88773178]
# 74

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89111374]
 [0.86537205]
 [0.89326958]]
Loss: 
0.0002913217364485442


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.88792512]
# 75

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89130359]
 [0.86558353]
 [0.89345828]]
Loss: 
0.00028887313070896154


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.88811176]
# 76

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89148687]
 [0.86578747]
 [0.89364033]]
Loss: 
0.00028658175243679435


Predicted data based on tr

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89309951]
# 142

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89639756]
 [0.87097042]
 [0.89839228]]
Loss: 
0.00024928516536395796


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.8931234]
# 143

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89642132]
 [0.87099042]
 [0.89841311]]
Loss: 
0.0002491746207017943


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89314665]
# 144

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89644446]
 [0.8710097 ]
 [0.89843331]]
Loss: 
0.00024906595333361884


Predicted data based on 

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89392596]
# 213

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89723252]
 [0.87140454]
 [0.89901096]]
Loss: 
0.0002432064223866111


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89393133]
# 214

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89723814]
 [0.87140357]
 [0.89901348]]
Loss: 
0.00024312890681844535


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89393663]
# 215

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89724368]
 [0.87140252]
 [0.89901593]]
Loss: 
0.00024305144954806952


Predicted data based on

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89752196]
 [0.8712344 ]
 [0.89908983]]
Loss: 
0.00023803306526251354


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89420044]
# 282

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89752548]
 [0.8712311 ]
 [0.89909026]]
Loss: 
0.0002379582261887019


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89420368]
# 283

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89752899]
 [0.8712278 ]
 [0.89909069]]
Loss: 
0.0002378834202803047


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.8942069]
# 284

Input (scaled): 
[[0.6666

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89440191]
# 348

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89774511]
 [0.8710024 ]
 [0.8991071 ]]
Loss: 
0.00023309081615064428


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89440485]
# 349

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89774833]
 [0.87099887]
 [0.89910726]]
Loss: 
0.000233018141302575


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.8944078]
# 350

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89775154]
 [0.87099534]
 [0.89910743]]
Loss: 
0.0002329454980838151


Predicted data based on tr

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89458818]
# 412

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89794845]
 [0.87077678]
 [0.89911583]]
Loss: 
0.00022850267992804673


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89459107]
# 413

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8979516 ]
 [0.87077327]
 [0.89911595]]
Loss: 
0.00022843199512700087


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89459395]
# 414

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89795474]
 [0.87076977]
 [0.89911607]]
Loss: 
0.00022836134087743222


Predicted data based o

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89478598]
# 481

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8981639 ]
 [0.87053715]
 [0.8991237 ]]
Loss: 
0.00022369624579162076


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89478884]
# 482

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.898167  ]
 [0.87053371]
 [0.89912381]]
Loss: 
0.00022362763080237608


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89479169]
# 483

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8981701 ]
 [0.87053027]
 [0.89912391]]
Loss: 
0.0002235590452467274


Predicted data based on

Predicted Output: 
[[0.89838562]
 [0.87029223]
 [0.89913122]]
Loss: 
0.0002188302587904078


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89499295]
# 554

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89838868]
 [0.87028887]
 [0.89913133]]
Loss: 
0.00021876372286134998


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89499577]
# 555

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89839173]
 [0.8702855 ]
 [0.89913143]]
Loss: 
0.00021869721524190002


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89499859]
# 556

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.

Loss: 
0.00021436954415913982


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89518379]
# 622

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89859532]
 [0.87006248]
 [0.89913787]]
Loss: 
0.00021430489880939994


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89518658]
# 623

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89859834]
 [0.87005919]
 [0.89913797]]
Loss: 
0.0002142402807464445


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89518937]
# 624

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89860136]
 [0.8700559 ]
 [0.89913806]]
Loss: 
0.00021417568995

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89536726]
# 688

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89879341]
 [0.8698472 ]
 [0.8991437 ]]
Loss: 
0.00021009793538526506


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89537002]
# 689

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.8987964 ]
 [0.86984397]
 [0.89914378]]
Loss: 
0.0002100350859738592


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89537279]
# 690

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89879938]
 [0.86984074]
 [0.89914386]]
Loss: 
0.0002099722628770368


Predicted data based on 

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89557096]
# 762

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89901268]
 [0.86961092]
 [0.89914956]]
Loss: 
0.00020551723962897587


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89557369]
# 763

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89901562]
 [0.86960776]
 [0.89914963]]
Loss: 
0.00020545629949804566


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89557643]
# 764

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89901857]
 [0.86960461]
 [0.89914971]]
Loss: 
0.0002053953846475398


Predicted data based on

Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89574545]
# 826

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89919994]
 [0.86941083]
 [0.89915403]]
Loss: 
0.00020166747052341008


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89574816]
# 827

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89920285]
 [0.86940774]
 [0.89915409]]
Loss: 
0.00020160812102851678


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89575087]
# 828

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89920576]
 [0.86940464]
 [0.89915416]]
Loss: 
0.00020154879595202617


Predicted data based o

0.00019774441475161543


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89592917]
# 894

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89939653]
 [0.86920249]
 [0.89915813]]
Loss: 
0.00019768667236035238


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89593186]
# 895

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89939941]
 [0.86919945]
 [0.89915819]]
Loss: 
0.00019762895351614079


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89593455]
# 896

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89940228]
 [0.86919642]
 [0.89915824]]
Loss: 
0.000197571258206204



Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89960207]
 [0.86898656]
 [0.89916173]]
Loss: 
0.0001935903149926824


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89612452]
# 967

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89960491]
 [0.86898359]
 [0.89916177]]
Loss: 
0.00019353425839852356


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89612718]
# 968

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.89960774]
 [0.86898063]
 [0.89916182]]
Loss: 
0.00019347822443698386


Predicted data based on trained weights: 
Input (scaled): 
[0.5 1. ]
Output: 
[0.89612984]
# 969

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]